ARTIFACT_DIR = ENV.fetch('ARTIFACT_DIR', './')
VAULT_IMAGE_VERSION = ENV.fetch('VAULT_IMAGE_VERSION', 'undefined')
MEMORY_SIZE = ENV.fetch('MEMORY_SIZE', 2048).to_i
CPUS = ENV.fetch('CPUS', 3).to_i

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"

  config.vm.box = "#{ARTIFACT_DIR}/vault/#{VAULT_IMAGE_VERSION}/vault-#{VAULT_IMAGE_VERSION}.box"
  config.vm.boot_timeout = 900
  config.ssh.username = "ansible"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.define "vault" do |node|
    # Name shown in the GUI
    node.vm.provider "virtualbox" do |vb|
      vb.name = "vault"
      vb.memory = "#{MEMORY_SIZE}"
      vb.cpus = "#{CPUS}"
    end
  end
end